"""empty message

Revision ID: 38a4a543ef48
Revises: 3c97a3b40fa5
Create Date: 2024-05-10 21:04:20.303563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a4a543ef48'
down_revision = '3c97a3b40fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('nacimiento', sa.String(length=120), nullable=False),
    sa.Column('especie', sa.String(length=120), nullable=False),
    sa.Column('altura', sa.String(length=120), nullable=False),
    sa.Column('peso', sa.String(length=120), nullable=False),
    sa.Column('genero', sa.String(length=120), nullable=False),
    sa.Column('color_pelo', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('altura'),
    sa.UniqueConstraint('color_pelo'),
    sa.UniqueConstraint('especie'),
    sa.UniqueConstraint('genero'),
    sa.UniqueConstraint('nacimiento'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('peso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planetas')
    # ### end Alembic commands ###
