"""empty message

Revision ID: 77552e532957
Revises: 8d0dd61fdb88
Create Date: 2024-05-15 22:10:43.486513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77552e532957'
down_revision = '8d0dd61fdb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos__planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planetas_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planetas', ['planetas_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos__planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planetas_id')

    # ### end Alembic commands ###
