"""empty message

Revision ID: 8d0dd61fdb88
Revises: 6e3c2f2a02c3
Create Date: 2024-05-14 08:30:32.697856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0dd61fdb88'
down_revision = '6e3c2f2a02c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favoritos__planetas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('favoritos_p', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personajes_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'personajes', ['personajes_id'], ['id'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favoritos_p', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('personajes_id')

    op.drop_table('favoritos__planetas')
    # ### end Alembic commands ###
