"""empty message

Revision ID: 950802d07d15
Revises: c5b0fb025329
Create Date: 2024-05-10 21:10:01.192623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950802d07d15'
down_revision = 'c5b0fb025329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nacimiento', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('especie', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('altura', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('peso', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('genero', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('color_pelo', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('personajes_apellido_key', type_='unique')
        batch_op.drop_constraint('personajes_ciudad_key', type_='unique')
        batch_op.create_unique_constraint(None, ['nacimiento'])
        batch_op.create_unique_constraint(None, ['especie'])
        batch_op.create_unique_constraint(None, ['altura'])
        batch_op.create_unique_constraint(None, ['peso'])
        batch_op.create_unique_constraint(None, ['genero'])
        batch_op.create_unique_constraint(None, ['color_pelo'])
        batch_op.drop_column('apellido')
        batch_op.drop_column('ciudad')

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('terreno', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('clima', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('planetas_Name_key', type_='unique')
        batch_op.drop_constraint('planetas_altura_key', type_='unique')
        batch_op.drop_constraint('planetas_color_pelo_key', type_='unique')
        batch_op.drop_constraint('planetas_especie_key', type_='unique')
        batch_op.drop_constraint('planetas_genero_key', type_='unique')
        batch_op.drop_constraint('planetas_nacimiento_key', type_='unique')
        batch_op.drop_constraint('planetas_peso_key', type_='unique')
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['clima'])
        batch_op.create_unique_constraint(None, ['terreno'])
        batch_op.drop_column('genero')
        batch_op.drop_column('peso')
        batch_op.drop_column('altura')
        batch_op.drop_column('nacimiento')
        batch_op.drop_column('color_pelo')
        batch_op.drop_column('especie')
        batch_op.drop_column('Name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('especie', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('color_pelo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nacimiento', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('altura', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('peso', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('genero', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('planetas_peso_key', ['peso'])
        batch_op.create_unique_constraint('planetas_nacimiento_key', ['nacimiento'])
        batch_op.create_unique_constraint('planetas_genero_key', ['genero'])
        batch_op.create_unique_constraint('planetas_especie_key', ['especie'])
        batch_op.create_unique_constraint('planetas_color_pelo_key', ['color_pelo'])
        batch_op.create_unique_constraint('planetas_altura_key', ['altura'])
        batch_op.create_unique_constraint('planetas_Name_key', ['Name'])
        batch_op.drop_column('clima')
        batch_op.drop_column('terreno')
        batch_op.drop_column('name')

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('apellido', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('personajes_ciudad_key', ['ciudad'])
        batch_op.create_unique_constraint('personajes_apellido_key', ['apellido'])
        batch_op.drop_column('color_pelo')
        batch_op.drop_column('genero')
        batch_op.drop_column('peso')
        batch_op.drop_column('altura')
        batch_op.drop_column('especie')
        batch_op.drop_column('nacimiento')

    # ### end Alembic commands ###
