"""empty message

Revision ID: c5b0fb025329
Revises: 38a4a543ef48
Create Date: 2024-05-10 21:06:56.151769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b0fb025329'
down_revision = '38a4a543ef48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('planetas_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['Name'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('planetas_name_key', ['name'])
        batch_op.drop_column('Name')

    # ### end Alembic commands ###
