"""empty message

Revision ID: f1b1e43c7457
Revises: 950802d07d15
Create Date: 2024-05-10 22:46:20.947786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b1e43c7457'
down_revision = '950802d07d15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('Model', sa.String(length=120), nullable=False),
    sa.Column('Manufacturer', sa.String(length=120), nullable=False),
    sa.Column('Class', sa.String(length=120), nullable=False),
    sa.Column('Cargo_Capacity', sa.String(length=120), nullable=False),
    sa.Column('Length', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Cargo_Capacity'),
    sa.UniqueConstraint('Class'),
    sa.UniqueConstraint('Length'),
    sa.UniqueConstraint('Manufacturer'),
    sa.UniqueConstraint('Model'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculos')
    # ### end Alembic commands ###
